defmodule WandererApp.Repo.Migrations.AddMapDiscordHome do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:maps_v1) do
      add :discord_webhook_url, :text
      add :home_solar_system_id, :bigint
    end
  end

  def down do
    alter table(:maps_v1) do
      remove :home_solar_system_id
      remove :discord_webhook_url
    end
  end
end
