defmodule WandererApp.Repo.Migrations.ShareWholeMap do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:maps_v1) do
      add :home_share_full, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:maps_v1) do
      remove :home_share_full
    end
  end
end
