defmodule WandererApp.Repo.Migrations.AddMapDiscordDigest do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:maps_v1) do
      add :discord_last_digest, :bigint
    end
  end

  def down do
    alter table(:maps_v1) do
      remove :discord_last_digest
    end
  end
end
