defmodule WandererApp.Repo.Migrations.AddMapBridges do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:map_bridges_v1, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :solar_system_source, :bigint, null: false
      add :solar_system_target, :bigint, null: false
      add :dangerous, :boolean, null: false, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :map_id,
          references(:maps_v1,
            column: :id,
            name: "map_bridges_v1_map_id_fkey",
            type: :uuid,
            on_delete: :delete_all
          )
    end

    create unique_index(:map_bridges_v1, [:map_id, :solar_system_source, :solar_system_target],
             name: "map_bridges_v1_unique_bridge_index"
           )
  end

  def down do
    drop_if_exists unique_index(
                     :map_bridges_v1,
                     [:map_id, :solar_system_source, :solar_system_target],
                     name: "map_bridges_v1_unique_bridge_index"
                   )

    drop constraint(:map_bridges_v1, "map_bridges_v1_map_id_fkey")

    drop table(:map_bridges_v1)
  end
end
