defmodule WandererApp.Repo.Migrations.SyncUpstreamSnapshots do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:maps_v1) do
      modify :scopes, {:array, :text}, default: ["wormholes"]
    end

    drop constraint(:map_chain_v1, "map_chain_v1_locked_by_id_fkey")

    alter table(:map_chain_v1) do
      modify :locked_by_id,
             references(:character_v1,
               column: :id,
               name: "map_chain_v1_locked_by_id_fkey",
               type: :uuid,
               on_delete: :nilify_all
             )
    end
  end

  def down do
    drop constraint(:map_chain_v1, "map_chain_v1_locked_by_id_fkey")

    alter table(:map_chain_v1) do
      modify :locked_by_id,
             references(:character_v1,
               column: :id,
               name: "map_chain_v1_locked_by_id_fkey",
               type: :uuid
             )
    end

    alter table(:maps_v1) do
      modify :scopes, {:array, :text}, default: ~c"{wormholes}"
    end
  end
end
