defmodule WandererApp.Repo.Migrations.AddMapHubSystem do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:maps_v1) do
      add :hub_solar_system_id, :bigint
    end
  end

  def down do
    alter table(:maps_v1) do
      remove :hub_solar_system_id
    end
  end
end
