defmodule WandererApp.Repo.Migrations.HomeShareLocalBaseUrl do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:map_home_shares_v1) do
      modify :base_url, :text, null: false, default: ""
    end
  end

  def down do
    alter table(:map_home_shares_v1) do
      modify :base_url, :text, null: true, default: nil
    end
  end
end
