defmodule WandererApp.Repo.Migrations.AddAclDiscordRoles do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:access_lists_v1) do
      add :discord_guild_id, :text
    end

    alter table(:access_list_members_v1) do
      add :discord_role_id, :text
    end

    create unique_index(:access_list_members_v1, [:access_list_id, :discord_role_id],
             name: "access_list_members_v1_uniq_acl_discord_role_id_index"
           )
  end

  def down do
    drop_if_exists unique_index(:access_list_members_v1, [:access_list_id, :discord_role_id],
                     name: "access_list_members_v1_uniq_acl_discord_role_id_index"
                   )

    alter table(:access_list_members_v1) do
      remove :discord_role_id
    end

    alter table(:access_lists_v1) do
      remove :discord_guild_id
    end
  end
end
