defmodule WandererApp.Repo.Migrations.SystemKillsHours do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:system_kills_hours_v1, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :hour, :utc_datetime, null: false
      add :npc_kills, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:system_kills_hours_v1, [:hour],
             name: "system_kills_hours_v1_unique_hour_index"
           )
  end

  def down do
    drop_if_exists unique_index(:system_kills_hours_v1, [:hour],
                     name: "system_kills_hours_v1_unique_hour_index"
                   )

    drop table(:system_kills_hours_v1)
  end
end
