defmodule WandererApp.Repo.Migrations.AddMapDiscordThera do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:maps_v1) do
      add :discord_include_thera, :boolean, null: false, default: true
    end
  end

  def down do
    alter table(:maps_v1) do
      remove :discord_include_thera
    end
  end
end
