defmodule WandererApp.Repo.Migrations.AddUserDiscordIdentity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user_v1) do
      add :discord_user_id, :text
      add :discord_username, :text
      add :discord_linked_at, :utc_datetime_usec
    end

    create unique_index(:user_v1, [:discord_user_id],
             name: "user_v1_unique_discord_user_id_index"
           )
  end

  def down do
    drop_if_exists unique_index(:user_v1, [:discord_user_id],
                     name: "user_v1_unique_discord_user_id_index"
                   )

    alter table(:user_v1) do
      remove :discord_linked_at
      remove :discord_username
      remove :discord_user_id
    end
  end
end
