defmodule WandererApp.Repo.Migrations.AddMapHomeSharing do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:maps_v1) do
      add :home_share_token, :text
    end

    create table(:map_home_shares_v1, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :label, :text
      add :base_url, :text
      add :slug, :text, null: false
      add :token, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :map_id,
          references(:maps_v1,
            column: :id,
            name: "map_home_shares_v1_map_id_fkey",
            type: :uuid,
            on_delete: :delete_all
          )
    end

    create unique_index(:map_home_shares_v1, [:map_id, :base_url, :slug],
             name: "map_home_shares_v1_unique_share_index"
           )
  end

  def down do
    drop_if_exists unique_index(:map_home_shares_v1, [:map_id, :base_url, :slug],
                     name: "map_home_shares_v1_unique_share_index"
                   )

    drop constraint(:map_home_shares_v1, "map_home_shares_v1_map_id_fkey")

    drop table(:map_home_shares_v1)

    alter table(:maps_v1) do
      remove :home_share_token
    end
  end
end
